src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\EventRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: EventRepository::class)]
/**
 * @Vich\Uploadable
 */
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $title;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $place;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $organizedBy;

    #[ORM\Column(type: 'text', nullable: true)]
    private $description;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $imageSize;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $updatedAt;
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="events", fileNameProperty="imageName", size="imageSize")
     * 
     * @var File|null
     */
    private $imageFile;

    #[ORM\Column(type: 'boolean')]
    private $isBest;

    #[ORM\Column(type: 'string', length: 255)]
    private $Day;

    #[ORM\Column(type: 'string', length: 255)]
    private $Month;

    #[ORM\Column(type: 'string', length: 255)]
    private $year;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getOrganizedBy(): ?string
    {
        return $this->organizedBy;
    }

    public function setOrganizedBy(?string $organizedBy): self
    {
        $this->organizedBy = $organizedBy;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function setImageSize(?int $imageSize): self
    {
        $this->imageSize = $imageSize;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getIsBest(): ?bool
    {
        return $this->isBest;
    }

    public function setIsBest(bool $isBest): self
    {
        $this->isBest = $isBest;

        return $this;
    }

    public function getDay(): ?string
    {
        return $this->Day;
    }

    public function setDay(string $Day): self
    {
        $this->Day = $Day;

        return $this;
    }

    public function getMonth(): ?string
    {
        return $this->Month;
    }

    public function setMonth(string $Month): self
    {
        $this->Month = $Month;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(string $year): self
    {
        $this->year = $year;

        return $this;
    }
}

templates/evenements/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association Lamp - {{ event.title}}{% endblock %}


{% block body %}
<div class="container-fluid">
<div class="row my-5">
<div class="col-md-5">
<img src="{{ asset('images/events/' ~ event.imageName)}}" alt="{{ event.title}}" class="img-fluid mx-auto d-block" height="100px">
<div class="date mt-4">
<div class="dateRight">
<div id="number">{{event.day}}</div>
<div id="dateText">
<div id="mois">{{event.month}}</div>    
<div id="anee">{{event.year}}</div>
</div> 
</div>
</div> 
</div>
<div class="col-md-7 align-self-center">
<h4 class="text-center mt-4">{{ event.title}}</h4>

<p>{{ event.description}}</p>
{# </div>  #}
    </div>{# .col-md-7 #}
</div> 
</div>
</div>

<a href="{{ path('app_events')}}" class="btn btn-secondary my-3 d-grid gap-2 col-2 mx-auto">Autres Evenements</a>
{% endblock %}

templates/evenements/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Association Lamp - Evenements{% endblock %}


{% block body %}
<div class="container-fluid">
<div class="header-custom hc-evenements">
</div>
<h2 class="titre-prin-pag"> Evenements</h2>

<div class="row my-5">
{% for event in events %}
<div class="col-lg-4 event">
<h2 class="titre-event">{{ event.title}}</h2>  
<div class="date">
<div class="dateRight">
<div id="number">{{event.day}}</div>
<div id="dateText">
<div id="mois">{{event.month}}</div>    
<div id="anee">{{event.year}}</div>
</div> 
</div>
</div>  
<a href="{{ path('app_event_detail', {'slug' : event.id} )}}">
<img src="{{ asset('images/events/' ~ event.imageName)}}" alt="{{ event.title}}" class="img-fluid mx-auto d-block" height="100px">
</a>
<p class="para-present">{{ event.description}}</p>
</div>
    {% endfor %}
</div>
</div>

{% endblock %}